# Generated by Django 2.2.2 on 2019-07-05 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetName', models.CharField(max_length=40)),
                ('asset_image', models.FileField(blank=True, null=True, upload_to='')),
                ('image_size', models.SmallIntegerField(blank=True, null=True)),
                ('texto', models.CharField(blank=True, max_length=300, null=True)),
                ('text_size', models.SmallIntegerField(blank=True, null=True)),
                ('text_font', models.CharField(blank=True, max_length=20, null=True)),
                ('text_color', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('short_empresa', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProyecto', models.CharField(max_length=60)),
                ('fechaProyecto', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=80)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='')),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='mdesigner.Empresa')),
                ('group', models.ForeignKey(default='D', on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='mdesigner.Tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTarget', models.CharField(max_length=100)),
                ('short_target', models.CharField(blank=True, max_length=6, null=True)),
                ('LLN', models.CharField(blank=True, max_length=40, null=True)),
                ('asset1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset1', to='mdesigner.Assets')),
                ('asset2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset2', to='mdesigner.Assets')),
                ('asset3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset3', to='mdesigner.Assets')),
                ('asset4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset4', to='mdesigner.Assets')),
                ('asset5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset5', to='mdesigner.Assets')),
                ('asset6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset6', to='mdesigner.Assets')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='mdesigner.Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='mdesigner.Usuario'),
        ),
        migrations.CreateModel(
            name='eMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailName', models.CharField(max_length=50)),
                ('finalhtml', models.CharField(max_length=2000)),
                ('cssfolder', models.FileField(blank=True, null=True, upload_to='')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='mdesigner.Target')),
            ],
        ),
    ]
