# Generated by Django 2.2.2 on 2019-07-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdesigner', '0003_auto_20190709_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='username',
        ),
    ]
